# request service message to get states of robot_name
string robot_name
---
# result is current position expressed in [x, y, yaw]
float64[] current_position
float64 max_lin_velocity
float64 distance_remaining
bool is_robot_connected
bool is_navigation_completed
